gcp:
  project-id: <<GOOGLE_PROJECT_ID>>
  pub-sub:
    topic-name: <<PUBSUB_TOPIC_NAME>>
    subscription: <<PUBSUB_SUBSCRIPTION>>
    publisher:
      executor-thread-count: 4
      retry-settings:
        retry-delay: 5
        retry-delay-multiplier: 2.0
        max-retry-delay: 60
        total-timeout: 60
        initial-rpc-timeout: 10
        max-rpc-timeout: 10

email-system-sender:
  address: <<EMAIL_SYSTEM_SENDER>>

resilience4j:
  circuit-breaker:
    failure-rate-threshold: 50
    duration-in-open-state-ms: 2000
    ring-buffer-size-half-open-state: 10
    ring-buffer-size-closed-state: 100
  retry:
    max-attempts: 2
    wait-duration-ms: 500